name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # 使用与 GitHub Pages 兼容的 Ruby 版本

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler -v 2.4.22  # 安装与 Ruby 2.7 兼容的 Bundler 版本
          bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
